[mcp_servers.code-review-graph]
args = [
    "code-review-graph",
    "serve",
]
command = "uvx"

[mcp_servers.code-review-graph.tools.find_large_functions_tool]
approval_mode = "approve"

[mcp_servers.code-review-graph.tools.list_graph_stats_tool]
approval_mode = "approve"
